[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/forgot-password"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reset-password/:token"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/email-verification"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/email-verification/:token"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/error"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/new"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/user/:accessToken/:refreshToken"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/product/:productTitle/:productId"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/collection/:collectionTitle/:collectionId"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://shoeshubbackend.onrender.com/api/:splat"
  status = 200
  force = true
